language: common-lisp

os:
  - linux
  - osx

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libev-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  # for thread-support on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ros install sbcl; fi
  - ros install prove

before_script:
  - ros run -- --version

script:
  - run-prove woo-test.asd
