language: common-lisp

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

env:
  matrix:
    - LISP=sbcl

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libev-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/travis-install.sh | sh

before_script:
  - git clone https://github.com/fukamachi/lev ~/lisp/lev
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http

script:
  - ros -s prove
        -e '(or (prove:run :woo-test)
                (uiop:quit -1))'
