language: common-lisp
sudo: false

os:
  - linux
  - osx

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin

addons:
  apt:
    packages:
      - libev-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then benchmark/install-wrk.sh; fi
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  # for thread-support on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ros install sbcl; fi
  - ros install prove
  - git clone https://github.com/fukamachi/clack ~/lisp/clack
  - git clone https://github.com/fukamachi/quri ~/lisp/quri

before_script:
  - ros run -- --version

script:
  - run-prove woo-test.asd
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then benchmark/run-benchmark benchmark/woo/run; fi
