language: common-lisp
sudo: false

os:
  - linux
  - osx

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin

addons:
  apt:
    packages:
      - libev-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi
  - if ! $(which ros >/dev/null); then
      curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh;
    else
      ros -e '(ql:update-all-dists :prompt nil)';
    fi
  # for thread-support on OS X
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ros install sbcl; fi
  - ros install prove
  - git clone https://github.com/fukamachi/clack ~/lisp/clack

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros run -- --version

script:
  - run-prove woo-test.asd
