language: common-lisp

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

env:
  matrix:
    - LISP=sbcl

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libev-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libev; fi

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/fukamachi/cl-travis/multi-os/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/lev ~/lisp/lev
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http

script:
  - cl -l prove
       -e '(or (prove:run :woo-test)
               (uiop:quit -1))'
